# Generated by Django 5.0.6 on 2024-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_rename_user_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ON', 'online'), ('OF', 'ofline'), ('IG', 'ingame')], default='online', max_length=50),
        ),
    ]
