# Generated by Django 5.0.6 on 2024-06-03 10:25

import tournament_app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='four players', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('CLOSED', 'closed')], default=tournament_app.enums.Tourn_status['PENDING'], max_length=50)),
                ('round', models.CharField(choices=tournament_app.enums.Round.choices, default=tournament_app.enums.Round['HALF'], max_length=50)),
            ],
        ),
    ]
