# Generated by Django 5.0.6 on 2024-06-03 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
