# Generated by Django 5.0.6 on 2024-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0002_tournament_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CLOSED', 'closed')], default='pending', max_length=50),
        ),
    ]
