# Generated by Django 5.0.6 on 2024-07-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
        ('tournament_app', '0002_player_matche'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='authentication_app.user_profile'),
        ),
    ]
