# Generated by Django 5.0.6 on 2024-06-03 14:29

import tournament_app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_alter_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='round',
            field=models.CharField(choices=tournament_app.enums.Round.choices, default=4, max_length=50),
        ),
    ]
