# Generated by Django 5.0.6 on 2024-07-09 17:32

import tournament_app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_player_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matche',
            name='round',
            field=models.CharField(choices=[('QU', 'quarter'), ('HF', 'half'), ('FN', 'final')], default='half', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round',
            field=models.CharField(choices=tournament_app.enums.Round.choices, default='half', max_length=50),
        ),
    ]
