# Generated by Django 5.0.6 on 2024-06-03 14:31

import tournament_app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0004_alter_tournament_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CLOSED', 'closed')], default=tournament_app.enums.Tourn_status['PENDING'], max_length=50),
        ),
    ]
