# Generated by Django 5.0.6 on 2024-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0006_matche_winner_player_created_at_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('ON', 'online'), ('OF', 'ofline'), ('IG', 'ingame')], default='online', max_length=50),
        ),
    ]
