# Generated by Django 5.0.6 on 2024-06-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0007_matche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matche',
            name='tourn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament_app.tournament'),
        ),
    ]
