# Generated by Django 5.0.6 on 2024-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0007_alter_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PN', 'pending'), ('ST', 'start'), ('EN', 'end')], default='pending', max_length=50),
        ),
    ]
