# Generated by Django 5.0.6 on 2024-07-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0009_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matche',
            name='player1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='tournament_app.player'),
        ),
        migrations.AlterField(
            model_name='matche',
            name='player2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='tournament_app.player'),
        ),
    ]
