# Generated by Django 5.0.6 on 2024-07-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0010_alter_matche_player1_alter_matche_player2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='profile',
        ),
    ]
